<?php

namespace AppBundle\Repository;

/**
 * MessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessRepository extends \Doctrine\ORM\EntityRepository
{
}
