app_user:
    resource: "@AppBundle/Controller/UserController.php"
    prefix: /admin/
    type:     annotation

app_stage:
    resource: "@AppBundle/Controller/StageController.php"
    prefix: /admin/
    type:     annotation

app_competence:
    resource: "@AppBundle/Controller/CompetenceController.php"
    prefix: /admin/
    type:     annotation

app_entreprise:
    resource: "@AppBundle/Controller/EntrepriseController.php"
    prefix: /admin/
    type:     annotation

app_promotion:
    resource: "@AppBundle/Controller/PromotionController.php"
    prefix: /admin/
    type:     annotation

app_faireparti:
    resource: "@AppBundle/Controller/FairepartiController.php"
    prefix: /admin/
    type:     annotation

app_produit:
    resource: "@AppBundle/Controller/ProduitController.php"
    prefix: /admin/
    type:     annotation

app_stage:
    resource: "@AppBundle/Controller/StageController.php"
    prefix: /admin/
    type:     annotation

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
rest: 
    type: rest 
    resource: "routing_rest.yml"
    prefix:   /api 

app_fichesuivie:
    resource: "@AppBundle/Controller/FichesuivieController.php"
    type:     annotation

app_faireparti:
    resource: "@AppBundle/Controller/FairepartiController.php"
    type:     annotation

app_entreprise:
    resource: "@AppBundle/Controller/EntrepriseController.php"
    type:     annotation

app_contenu:
    resource: "@AppBundle/Controller/ContenuController.php"
    type:     annotation

app_commande:
    resource: "@AppBundle/Controller/CommandeController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    prefix: /admin/
    type:     annotation

app_competence:
    resource: "@AppBundle/Controller/CompetenceController.php"
    prefix: /admin/
    type:     annotation

stage:
    resource: "@StageBundle/Resources/config/routing.yml"
    prefix:   /admin/

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /admin/

app:
    resource: "@AppBundle/Controller/WelcomeController.php"
    prefix: /
    type:     annotation
