# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#parameters:

services:
  app.mailer: 
    class: AppBundle\Service\Mailer
    arguments: [mailer]

  app.security:
    class: AppBundle\Service\Security
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - UserBundle\Repository\AccessTokenRepository